### ISSUE TITLE
关闭预览，再重新打开预览，闪退

### ISSUE THREAD

**Issue by poikl369** [kaisa695275735/filter_camera#2]
报错信息是：
E/AndroidRuntime(28469): java.lang.IllegalStateException: Unable to update texture contents (see logcat for details)
E/AndroidRuntime(28469): 	at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/AndroidRuntime(28469): 	at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:243)
E/AndroidRuntime(28469): 	at me.ly.flutter_camera_copy.FilterCamera.onFrameAvailable(FilterCamera.java:151)
E/AndroidRuntime(28469): 	at android.graphics.SurfaceTexture$1.handleMessage(SurfaceTexture.java:206)
E/AndroidRuntime(28469): 	at android.os.Handler.dispatchMessage(Handler.java:106)
E/AndroidRuntime(28469): 	at android.os.Looper.loop(Looper.java:214)
E/AndroidRuntime(28469): 	at me.ly.flutter_camera_copy.FilterTexture1$1.run(FilterTexture1.java:64)
E/AndroidRuntime(28469): 	at java.lang.Thread.run(Thread.java:764)

**Comment by poikl369** [comment]
这代码的gl release有问题。
